version: 2

jobs:
  build-linux-gcc:
    docker:
      - image: outpostuniverse/nas2d-gcc:1.3
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make --keep-going config=default nas2d
      - run: make --keep-going config=default

workflows:
  version: 2
  build:
    jobs:
      - build-linux-gcc
