version: 2

jobs:
  build-linux-gcc:
    docker:
      - image: outpostuniverse/nas2d-circleci:1.1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make --keep-going config=gcc

workflows:
  version: 2
  build:
    jobs:
      - build-linux-gcc
