version: 2

jobs:
  gcc:
    docker:
      - image: outpostuniverse/nas2d-circleci:1.1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: make -k config=gcc

workflows:
  version: 2
  build:
    jobs:
      - gcc
