name: Build

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        configuration: [Release]
    runs-on: windows-latest
    env:
      Platform: ${{ matrix.platform }}
      Configuration: ${{ matrix.configuration }}
      VcpkgManifestInstall: false

    steps:
    - uses: actions/checkout@v6

    - name: Checkout submodules
      run: git submodule update --init

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Integrate vcpkg
      run: |
        vcpkg --version
        vcpkg integrate install

    - name: Restore vcpkg dependency cache
      uses: actions/cache/restore@v5
      id: cacheRestoreVcpkg
      with:
        path: vcpkg_installed\
        key: vcpkgCache-${{ runner.os }}-${{ matrix.platform }}-${{ hashFiles('vcpkg.json') }}

    - name: Install vcpkg dependencies
      if: steps.cacheRestoreVcpkg.outputs.cache-hit != 'true'
      env:
        VcpkgManifestInstall: true
      run: |
        msbuild /target:OP2-Landlord:VcpkgInstallManifestDependencies

    - name: Save vcpkg dependency cache
      uses: actions/cache/save@v5
      if: steps.cacheRestoreVcpkg.outputs.cache-hit != 'true'
      with:
        path: vcpkg_installed\
        key: ${{ steps.cacheRestoreVcpkg.outputs.cache-primary-key }}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /maxCpuCount

  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/outpostuniverse/op2-landlord:1.0
      env:
        CXX: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - run: make --keep-going
